# -*- coding: utf-8 -*-
"""Untitled1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1p9CgRgCl7KoNwf2bXXcHJBOy3Ly5o4Y_
"""

# Commented out IPython magic to ensure Python compatibility.
# %pip install pandas torch torch-geometric scikit-learn numpy

import pandas as pd
import torch
import torch.nn.functional as F
from torch_geometric.data import Data
from torch_geometric.nn import SAGEConv
from sklearn.metrics import f1_score, precision_recall_curve, auc
from sklearn.preprocessing import StandardScaler
import numpy as np

import os
import sys
classes_path = r"data/raw/elliptic_txs_classes.csv"
edgelist_path = r"data/raw/elliptic_txs_edgelist.csv"
features_path = r"data/raw/elliptic_txs_features.csv"

print(os.getcwd())

##################################################################################################################
#                                              1. Import data                                                    #
##################################################################################################################

# Import all Kaggle datasets
classes_df = pd.read_csv(classes_path)
edgelist_df = pd.read_csv(edgelist_path)
features_df = pd.read_csv(features_path, header=None)

# Manually add headers to third dataset since no headers are available for this data
features_df.columns = (
    ['txId', 'time_step'] +
    [f'feat_{i}' for i in range(features_df.shape[1] - 2)]
)

##################################################################################################################
#                                              2. Node indexing                                                  #
##################################################################################################################

all_tx_ids = features_df["txId"].values
tx_to_index = {tx: index for index, tx in enumerate(all_tx_ids)}
n_nodes = len(all_tx_ids)

##################################################################################################################
#                                              3. Node features                                                  #
##################################################################################################################

feature_matrix = features_df[[f"feat_{index}" for index in range(features_df.shape[1] - 2)]].values
scaler = StandardScaler()

feature_matrix = scaler.fit_transform(feature_matrix)
x = torch.tensor(feature_matrix, dtype=torch.float)

##################################################################################################################
#                                              4. Edge indexing                                                  #
##################################################################################################################

# Mask out all entries that have invalid transaction ID
mask = (
    edgelist_df["txId1"].isin(tx_to_index) &
    edgelist_df["txId2"].isin(tx_to_index)
)

edgelist_df = edgelist_df[mask]

source = edgelist_df["txId1"].map(tx_to_index).values
destination = edgelist_df["txId2"].map(tx_to_index).values

edge_index = torch.tensor([source, destination], dtype=torch.long)

##################################################################################################################
#                                              5. Labels (y)                                                     #
##################################################################################################################

# Mapping values
mapping = {
    "1": 1, # Illicit -> 1
    "2": 0, # Licit -> 0
    "unknown": -1 # Unknown -> -1
}

classes_df["label"] = classes_df["class"].map(mapping)

label_lookup = classes_df.set_index("txId")["label"].to_dict()
labels = [label_lookup.get(tx, -1) for tx in all_tx_ids]

y = torch.tensor(labels, dtype=torch.long)

##################################################################################################################
#                                             6. Train/Test/Val                                                  #
##################################################################################################################

time_steps = features_df["time_step"].values
labeled = (y != -1) # Exclude unknown data from training

##### Split #####
# Train: 1-34
# Val: 35-42
# Test: 43-49
#################

train_mask = labeled & torch.tensor(time_steps <= 34)
val_mask = labeled & torch.tensor((time_steps >= 35) & (time_steps <= 42))
test_mask = labeled & torch.tensor(time_steps >= 43)

##################################################################################################################
#                                             7. Class Weighting                                                 #
##################################################################################################################

train_labels = y[train_mask]
n_licit = (train_labels == 0).sum().item()
n_illicit = (train_labels == 1).sum().item()
class_weight = torch.tensor([1.0, n_licit / n_illicit], dtype=torch.float)

##################################################################################################################
#                                          8. PyTorch geometrics                                                 #
##################################################################################################################

data = Data(x=x,
            edge_index=edge_index,
            y=y,
            )

data.train_mask = train_mask
data.val_mask = val_mask
data.test_mask = test_mask

##################################################################################################################
#                                             9. GCN Engineering                                                 #
##################################################################################################################

class GraphSage(torch.nn.Module):
    def __init__(self, in_channels, hidden_channels, out_channels, dropout=0.5):
        super().__init__()
        self.conv1   = SAGEConv(in_channels, hidden_channels)
        self.conv2   = SAGEConv(hidden_channels, hidden_channels)
        self.conv3   = SAGEConv(hidden_channels, out_channels)
        self.dropout = dropout

    def forward(self, x, edge_index):
        x = F.relu(self.conv1(x, edge_index))
        x = F.dropout(x, p=self.dropout, training=self.training)
        x = F.relu(self.conv2(x, edge_index))
        x = F.dropout(x, p=self.dropout, training=self.training)
        return self.conv3(x, edge_index)

model     = GraphSage(in_channels=165, hidden_channels=256, out_channels=2, dropout=0.5)
optimizer = torch.optim.Adam(model.parameters(), lr=0.001, weight_decay=1e-4)
criterion = torch.nn.CrossEntropyLoss(weight=class_weight)

##################################################################################################################
#                                             10. Training Loop                                                  #
##################################################################################################################

best_val_f1 = 0.0
best_epoch = 0
patience = 50
epochs_no_imp = 0

def train():
    model.train()
    optimizer.zero_grad()
    out  = model(data.x, data.edge_index)
    loss = criterion(out[data.train_mask], data.y[data.train_mask])
    loss.backward()
    optimizer.step()
    return loss.item()

@torch.no_grad()
def evaluate_with_threshold(mask, threshold=0.5, verbose=False):
    model.eval()
    out              = model(data.x, data.edge_index)
    probs            = F.softmax(out, dim=1)[:, 1]
    preds            = (probs[mask] >= threshold).long().cpu().numpy()
    trues            = data.y[mask].cpu().numpy()
    p, r, thresholds = precision_recall_curve(trues, probs[mask].cpu().numpy())
    pr_auc           = auc(r, p)
    f1_scores        = 2 * (p * r) / (p + r + 1e-8)
    best_thresh      = thresholds[f1_scores[:-1].argmax()]
    best_f1          = f1_scores[:-1].max()

    if verbose:
        print(f"  Default threshold F1 : {f1_score(trues, preds, zero_division=0):.4f}")
        print(f"  Optimal threshold    : {best_thresh:.4f} → F1: {best_f1:.4f}")

    return best_f1, pr_auc, best_thresh

for epoch in range(1, 601):
    loss = train()
    f1, pr_auc, best_thresh = evaluate_with_threshold(data.val_mask)

    if f1 > best_val_f1:
        best_val_f1   = f1
        best_epoch    = epoch
        epochs_no_imp = 0
        torch.save(model.state_dict(), "best_model.pt")
    else:
        epochs_no_imp += 1

    if epoch % 20 == 0:
        print(f"Epoch {epoch:03d} | Loss: {loss:.4f} | Val F1: {f1:.4f} | PR-AUC: {pr_auc:.4f}")

    if epochs_no_imp >= patience:
        print(f"\nEarly stopping at epoch {epoch} — no improvement for {patience} epochs")
        break

print(f"\nBest Val F1: {best_val_f1:.4f} at epoch {best_epoch}")

##################################################################################################################
#                                             11. Test Evaluation + Save                                         #
##################################################################################################################

model.load_state_dict(torch.load("best_model.pt"))
print("\n--- Test Evaluation ---")
f1, pr_auc, best_thresh = evaluate_with_threshold(data.test_mask, verbose=True)
print(f"Test F1: {f1:.4f} | Test PR-AUC: {pr_auc:.4f} | Best Threshold: {best_thresh:.4f}")

torch.save({
    "data": data,
    "tx_to_index": tx_to_index,
    "best_thresh": best_thresh,
    "scaler": scaler
}, "graph_data.pt")

print("\nSaved → best_model.pt, graph_data.pt")

